# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

local_env = avango.build.PythonEnvironment()
avango.build.add_library(local_env, 'boost_python')
avango.build.add_library(local_env, 'avango-core')
avango.build.add_library(local_env, 'avango-python')
avango.build.add_library(local_env, 'avango-osg')

sound_files = Split("""
    _sound.cpp
    """)

sound_python_files = Split("""
    __init__.py
    """)

sound = local_env.SharedLibrary("_sound", sound_files)

local_env.Append(LIBS=['avangoSound'])
local_env.Depends(sound, sound_python_files)
local_env.Install(avango.build.get_python_path('avango/sound'), sound_python_files)
local_env.Install(avango.build.get_python_path('avango/sound'), sound)

Alias('sound', sound)
Alias('install-sound', avango.build.get_python_path('avango/sound'))
