# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

local_env = avango.build.PythonEnvironment()

avango.build.Environment.add_search_path('avango-python')

avango.build.add_library(local_env, 'avango-python')
avango.build.add_library(local_env, 'avango-core')

#local_env['CPPPATH'] += [ Dir('../src/avango/devices/multitouch') ]
#local_env['CPPPATH'] += [ Dir('../src/avango/devices/multitouch/oscpack') ]

local_env.Prepend(LIBS=['avangoDisplayMT'])

display_mt_files = Split("""
    _display_mt.cpp
    """)

display_mt_python_files = Split("""
    __init__.py
    """)

lib = local_env.SharedLibrary("_mt", display_mt_files)

local_env.Depends(lib, display_mt_python_files)
local_env.Install(avango.build.get_python_path('avango/display/mt'), display_mt_python_files)
local_env.Install(avango.build.get_python_path('avango/display/mt'), lib)
   
   
Alias('display', lib)
#issues the copying of the compiled lib to the installation folder
Alias('install-display', avango.build.get_python_path('avango/display/mt'))

