# -*- Mode:Python -*-

##########################################################################
#                                                                        #
#  Avango Software, Copyright 2001 - 2007 Fraunhofer Gesellschaft        #
#  zur Foerderung der angewandten Forschung (FhG), Munich, Germany.      #
#                                                                        #
#  Avango Software (both binary and source code - if released) is        #
#  intellectual property owned by FhG and copyrighted by FhG worldwide.  #
#                                                                        #
#  Avango is a trademark owned by FhG.                                   #
#                                                                        #
##########################################################################

import avango.build

local_env = avango.build.PythonEnvironment()

avango.build.Environment.add_search_path('avango-python')

avango.build.add_library(local_env, 'avango-python')
avango.build.add_library(local_env, 'avango-core')

#local_env['CPPPATH'] += [ Dir('../src/avango/devices/multitouch') ]
#local_env['CPPPATH'] += [ Dir('../src/avango/devices/multitouch/oscpack') ]

local_env.Prepend(LIBS=['avangoDisplayMT'])

display_mt_files = Split("""
    _display_mt.cpp
    """)

display_mt_python_files = Split("""
    __init__.py
    """)

lib = local_env.SharedLibrary("_mt", display_mt_files)

local_env.Depends(lib, display_mt_python_files)
local_env.Install(avango.build.get_python_path('avango/display/mt'), display_mt_python_files)
local_env.Install(avango.build.get_python_path('avango/display/mt'), lib)
   
   
Alias('display', lib)
#issues the copying of the compiled lib to the installation folder
Alias('install-display', avango.build.get_python_path('avango/display/mt'))

