# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

headers = Split('''
    ChangeSelector.h
    Doxygen.h
    Init.h
    InjectSelector.h
    ObjectSelector.h
    NameSelector.h
    FieldSelector.h
    Selector.h
    SingleSelector.h
    TargetHolder.h
    Tool.h
    TriggerSelector.h
    TypeSelector.h
    UnionSelector.h
    windows_specific_tools.h
    ''')

if avango.build.Environment()['OPENSCENEGRAPH_SUPPORT']:
    headers += Split('''
        DragTool.h
        IntersectionTargetHolder.h
        NodePathTargetHolder.h
        PickSelector.h
        ProximitySelector.h
        ScaledGrabTool.h
        ''')

Alias('install-tools', Install(avango.build.get_include_path('avango/tools'), headers))
