# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

import avango.build

avango.build.Environment.prepend_include_path(Dir('include').abspath)
avango.build.Environment.prepend_library_path(Dir('.').abspath)
local_env = avango.build.Environment()
avango.build.add_library(local_env, 'avango-sound')
avango.build.add_library(local_env, 'openal')
avango.build.add_library(local_env, 'alut')
avango.build.add_library(local_env, 'vorbisfile')


openal_files = Split('''
    src/OpenALSoundRenderer.cpp
    ''')
openal_lib = local_env.SharedLibrary('avangoOpenALSound', openal_files)
Alias('install-openal-sound', local_env.Install(avango.build.get_library_path(), openal_lib))

local_test_env = avango.build.TestEnvironment()
local_test_env.Append(LIBS=[openal_lib])

Alias('openal-sound', openal_lib)
Alias('all', Alias('openal-sound'))
Alias('check', Alias("check-openal-sound"))
Alias('install', Alias('install-openal-sound'))

SConscript ([
    'include/avango/sound/openal/SConscript',
    'src/tests/SConscript',
    'python/SConscript'
])
