# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

import avango.build

local_env = avango.build.PythonEnvironment()

daemon_files = Split("""
    _daemon.cpp
    """)

daemon_python_files = Split("""
    __init__.py
    """)

daemon = local_env.SharedLibrary("_daemon", daemon_files)

local_env.Append(LIBS=['avangoDaemon'])
local_env.Depends(daemon, daemon_python_files)
local_env.Install(avango.build.get_python_path('avango/daemon'), daemon_python_files)
local_env.Install(avango.build.get_python_path('avango/daemon'), daemon)

Alias('daemon', daemon)
Alias('install-daemon', avango.build.get_python_path('avango/daemon/'))
