# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

import avango.build
Import('moving_env')

sources = Split('''
    Init.cpp
    Trackball.cpp
    DesktopFlyer.cpp
    ''')

avango.build.add_library(moving_env, 'avango-osg')
avango.build.add_library(moving_env, 'avango-core')
moving_env.Append(CPPDEFINES='AV_MOVING_LIBRARY')
lib = moving_env.SharedLibrary('avangoMoving', sources)
Alias('moving', lib)
Alias('install-moving', Install(avango.build.get_library_path(), lib))

avango.build.Environment.prepend_library_path(Dir('.').abspath)
