# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

Import('avango_test_env')

tests = []

local_test_env = avango_test_env.Clone()
local_test_env['ENV']['HOME'] = Dir('InvalidHomeDirForEnsemble').abspath

test_net_node = local_test_env.Program(Split('''
                                             TestNetwork.cpp
                                             TestNetNode.cpp
                                             TestNetLock.cpp
                                             '''))
tests += local_test_env.Alias('test-core-network-net-node', test_net_node,
                              "${SOURCE.abspath}")

AlwaysBuild(tests)
Alias('check-core', Alias('check-core-network', tests))
