# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################


import avango.build

avango.build.setup()

env = avango.build.Environment()

used_libs = Split("""
    boost_thread
    boost_signals
    """)

for lib in used_libs:
    avango.build.Environment.add_search_path(lib)

avango.build.Environment.add_search_path('avango-core')
avango.build.Environment.add_search_path('avango-osg')
avango.build.Environment.add_search_path('avango-python')

avango.build.TestEnvironment.add_search_path('avango-unittest')
avango.build.TestEnvironment.add_library('avango-unittest')

avango.build.SConscript('SConscript')
