# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

Import('shade_core_libname')

sources = Split('''
    TestAvangoShade.cpp
    TestShader.cpp
    DummyShader.cpp
    DummyShaderWrapper.cpp
    ''')

local_test_env = avango.build.TestEnvironment()
local_test_env.Prepend(LIBS = ['avangoShade', shade_core_libname])

for lib in ['avango-core', 'avango-osg', 'osg']:
    avango.build.add_library(local_test_env, lib)

tests = local_test_env.Program ('TestAvangoShade', sources)
tests_alias = local_test_env.Alias('test-shade', tests, "${SOURCE.abspath}")

AlwaysBuild(tests_alias)
Alias('check-shade', tests_alias)
