# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2009 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

import avango.build

# guide environment
guide_env = avango.build.Environment()

# guide sources
guide_sources = Split("""
    index.html
    """)
guide_sources += Glob('guide/*')
guide_sources += Glob('guide/media/*')

# guide install
guide_install = guide_env.Install(
    avango.build.get_documentation_path().abspath,
    source = ['index.html', 'guide'])

guide_env.Clean(guide_install, avango.build.get_documentation_path().abspath + '/guide')

Alias('guide', guide_sources)
Alias('install-guide', ['guide', guide_install])


# doc subdirectories
SConscript ([
    'doxygen/SConscript',
    'epydoc/SConscript',
])

# doc aliases
Alias('doc', ['guide', 'doxygen', 'epydoc'])
Alias('install-doc', ['install-guide', 'install-doxygen', 'install-epydoc']);
