# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

Import('avango_test_env')

tests = []

test_lib_type = avango_test_env.Program(Split('TestLibType.cpp TestType.cpp'))
tests += avango_test_env.Alias('test-core-types-lib-type', test_lib_type,
                               "${SOURCE.abspath}")

test_container_pool = avango_test_env.Program('TestContainerPool', 'TestContainerPool.cpp')
tests += avango_test_env.Alias('test-core-types-container-pool', test_container_pool,
                               "${SOURCE.abspath}")

AlwaysBuild(tests)
Alias('check-core', Alias('check-core-types', tests))
