# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2009 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build
Import('sound_env')

sound_env.Append(CPPDEFINES='AV_SOUND_LIBRARY')

sources = Split('''
    SoundTraverser.cpp
    SoundSource.cpp
    SoundRenderer.cpp
    SampleBuffer.cpp
    ''')
    
if avango.build.oshelper.os_is_mac():
	avango.build.add_library(sound_env, "boost_system")
	
lib = sound_env.SharedLibrary('avangoSound', sources)
Alias('sound', lib)
Alias('install-sound', Install(avango.build.get_library_path(), lib))

avango.build.Environment.prepend_library_path(Dir('.').abspath)