# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################


import avango.build

opts = avango.build.options
opts.AddOptions(
    BoolOption('DISTRIBUTION_SUPPORT',
               'Switch to enable distribution support (requires ensemble module)',
               False),
    )

avango.build.setup()

env = avango.build.Environment()

if env['DISTRIBUTION_SUPPORT']:
    avango.build.Environment.add_search_path('avango-ensemble')

used_libs = Split("""
    dl
    boost_thread
    boost_signals
    """)
for lib in used_libs:
    avango.build.Environment.add_search_path(lib)

avango.build.TestEnvironment.add_search_path('avango-unittest')
avango.build.TestEnvironment.add_library('avango-unittest')

avango.build.SConscript('SConscript')
