# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build
shade_env = avango.build.Environment()

sources = Split('''
    FloatFieldAdapter.cpp
    Init.cpp
    IntFieldAdapter.cpp
    LightSource.cpp
    ListFieldAdapter.cpp
    ObjrefFieldAdapter.cpp
    Shader.cpp
    State.cpp
    StateGroup.cpp
    Types.cpp
    TextureFieldAdapter.cpp
    Vec2FieldAdapter.cpp
    Vec3FieldAdapter.cpp
    Vec4FieldAdapter.cpp
    MatrixFieldAdapter.cpp
    ''')

for lib in ['avango-core', 'avango-osg', 'osg']:
    avango.build.add_library(shade_env, lib)
shade_env.Append(CPPDEFINES='AV_SHADE_LIBRARY')
lib = shade_env.SharedLibrary('avangoShade', sources)
Depends(lib, Dir('../../include/avango/shade/impl')) # FIXME bug or bad behaviour in scons
Alias('shade', lib)
Alias('install-shade', Install(avango.build.get_library_path(), lib))

avango.build.Environment.prepend_library_path(Dir('.').abspath)
