# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

env = avango.build.Environment()
avango.build.add_library(env, 'avango-core')
avango.build.add_library(env, 'avango-osg')
avango.build.add_library(env, 'osg')

env.Append(CPPDEFINES='AV_UTILS_LIBRARY')

sources = Split('''
    Bool2Or.cpp
    Bool2And.cpp
    Bool3Or.cpp
    Bool3And.cpp
    ProximitySensor.cpp
    Init.cpp
    ''')

lib = env.SharedLibrary('avangoUtils', sources)
Alias('utils', lib)
Alias('install-utils', env.Install(avango.build.get_library_path(), lib))

avango.build.Environment.prepend_library_path(Dir('.').abspath)
