# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

sources = Split('''
    Main.cpp
    TestAssertHandler.cpp
    TestChecks.cpp
    TestUnitTest++.cpp
    TestTest.cpp
    TestTestResults.cpp
    TestTestRunner.cpp
    TestCheckMacros.cpp
    TestTestList.cpp
    TestTestMacros.cpp
    TestTimeConstraint.cpp
    TestTimeConstraintMacro.cpp
    TestMemoryOutStream.cpp
    TestDeferredTestReporter.cpp
    TestXmlTestReporter.cpp
    ''')

local_test_env = avango.build.TestEnvironment()
local_test_env.Append(LIBS = ['avangoUnitTest++'])

tests = local_test_env.Program('TestAvangoUnitTest++', sources)
tests_alias = local_test_env.Alias('test-unittest', tests, "${SOURCE.abspath}")

AlwaysBuild(tests_alias)
Alias('check-unittest', tests_alias)
