# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2009 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build
import avango.build.oshelper

avango.build.Environment.prepend_python_path(Dir('.').abspath)
module_env = avango.build.PythonEnvironment()
avango.build.add_library(module_env, 'boost_python')
avango.build.add_library(module_env, 'avango-core')
avango.build.add_library(module_env, 'avango-python')
if avango.build.oshelper.os_is_mac():
	avango.build.add_library(module_env, "boost_system")

module_env.Prepend(LIBS="avangoTools")

Alias('install-tools', avango.build.get_python_path('avango/tools'))

tools_files = Split("""
    avango/tools/_tools.cpp
    avango/tools/Selectors.cpp
    avango/tools/ScriptTool.cpp
    """)

if avango.build.Environment()['OPENSCENEGRAPH_SUPPORT']:
    tools_files += Split('''
        avango/tools/OSGTools.cpp
        ''')

tools_lib = module_env.SharedLibrary("avango/tools/_tools", tools_files)
tools_module = Alias('tools-python', [
    tools_lib,
    File("avango/tools/__init__.py"),
    ])
module_env.Install(avango.build.get_python_path('avango/tools'), "avango/tools/__init__.py")
module_env.Install(avango.build.get_python_path('avango/tools'), tools_lib)
Alias('tools', tools_module)
