# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

Import('avango_test_env')

tests = []

local_test_env = avango_test_env.Clone()
local_test_env['ENV']['AVANGO_TEST_LOG'] = File('test.log').abspath

test_logging = local_test_env.Program('TestLogging.cpp')
tests += local_test_env.Alias('test-core-logging', test_logging, "${SOURCE.abspath}")

AlwaysBuild(tests)
Alias('check-core', Alias('check-core-logging', tests))
