# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2009 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

import avango.build

Alias('install', Alias('install-examples'))

examples_dir = avango.build.get_documentation_path('examples')
Export('examples_dir')


# basic examples

if avango.build.Environment()['OPENSCENEGRAPH_SUPPORT']:
	SConscript('3d-menu/SConscript')
	SConscript('avango-tools/SConscript')
	SConscript('desktop-flyer/SConscript')
	SConscript('display-setup/SConscript')
	SConscript('embedded-viewer/SConscript')
	SConscript('inspector/SConscript')
	SConscript('layer/SConscript')
	SConscript('simple/SConscript')
	SConscript('snowland/SConscript')
	SConscript('wireframe/SConscript')


# examples requiring specific avango modules

if avango.build.Environment()['CONNECT_SUPPORT']:
	SConscript('connect/SConscript')
if avango.build.Environment()['OPENAL_SUPPORT']:
	SConscript('sound/SConscript')
if not avango.build.oshelper.os_is_windows() and \
	 not avango.build.oshelper.os_is_mac():
	SConscript('daemon/SConscript')
