# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

test_package_dir = '../test_package/'

avango_utils_test_files = Split("""
    TestProximitySensor.py
    TestBoolScripts.py
    TestMFMerger.py
    TestTriggers.py
    TestTaskScheduler.py
    TestNormalization.py
    TestConverters.py
    TestInterpolators.py
    TestMultiValueFields.py
    runtests.py
    __init__.py
    """)
avango.build.install_python(test_package_dir+'avango/utils/tests/', avango_utils_test_files)

test_env = avango.build.TestEnvironment()
check = test_env.Alias('test-utils', test_package_dir+'avango/utils/tests/runtests.pyc', 'python $SOURCE')
AlwaysBuild(check)
Alias('check-utils', check)
test_env.Depends(check, test_package_dir)
