# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2010 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

headers = Split('''
    avango/shade/Doxygen.h
    avango/shade/FieldAdapter.h
    avango/shade/Init.h
    avango/shade/LightSource.h
    avango/shade/Shader.h
    avango/shade/State.h
    avango/shade/StateGroup.h
    avango/shade/Types.h
    avango/shade/windows_specific_shade.h
    ''')

headers_impl = Split('''
    avango/shade/impl/Init_impl.cpp
    ''')

Alias('install-shade', Install(avango.build.get_include_path("avango/shade"), headers))
Alias('install-shade', Install(avango.build.get_include_path("avango/shade/impl"), headers_impl))

avango.build.Environment.prepend_include_path(Dir('.').abspath)
