# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of Avango.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# Avango is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# Avango is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with Avango. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
# Avango is a trademark owned by FhG.                                    #
#                                                                        #
##########################################################################

import avango.build

sources = Split('''
    TestOpenALSound.cpp
    TestOpenALSoundRenderer.cpp
    ''')

local_test_env = avango.build.TestEnvironment()
local_test_env.Append(LIBS = ['avangoOpenALSound'])

local_test_env.Prepend(LIBPATH=['../..'])
local_test_env.PrependENVPath(avango.build.get_library_search_path_env(), Dir('../..').abspath)

tests = local_test_env.Program ('TestOpenALSound', sources)
tests_alias = local_test_env.Alias('test-sound', tests, "${SOURCE.abspath}")

AlwaysBuild(tests_alias)
Alias('check-openal-sound', tests_alias)
