# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

Import('avango_test_env')

tests = []

test_nodes = avango_test_env.Program(Split('''
                                    TestNodes.cpp
                                    MockFieldContainer.cpp
                                    TestFieldContainer.cpp
                                    TestAbstractNode.cpp
                                    TestFieldConnectionChangeInNotify.cpp
                                    TestEvaluationOrder.cpp
                                    TestUnref.cpp
                                    '''))
tests += avango_test_env.Alias('test-core-nodes', test_nodes, "${SOURCE.abspath}")

AlwaysBuild(tests)
Alias('check-core', Alias('check-core-nodes', tests))
