# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

Import('avango_env')

if avango_env['DISTRIBUTION_SUPPORT']:

    SConscript('tests/SConscript')

    sources = Split('''
        Helper.cpp
        MaestroEID.cpp
        MaestroMerge.cpp
        Msg.cpp
        NetGroup.cpp
        NetID.cpp
        NetInfo.cpp
        NetLock.cpp
        NetMap.cpp
        NetNode.cpp
        UpcallSerializer.cpp
        ''')

    if avango_env['ZMQ_DISTRIBUTION_SUPPORT']:
        sources += Split('''
            NetNodeClient.cpp
            NetNodeServer.cpp
            ''')

    objects = avango_env.SharedObject(sources)

else:
    objects = []

Return('objects')
