# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2009 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build

local_test_env = avango.build.TestEnvironment()
if local_test_env['DISTRIBUTION_SUPPORT']:
    sources = Split('''
        TestAvangoOSGNetwork.cpp
        TestSharedContainerHolder.cpp
        ''')

    local_test_env.Append(LIBS = ['avangoOsg'])
    local_test_env.Append(LIBS = ['avangoOsgNetwork'])
    local_test_env.Prepend(LIBPATH=['..'])
    local_test_env.PrependENVPath(avango.build.get_library_search_path_env(), Dir('..').abspath)
    local_test_env.Prepend(LIBPATH=['../..'])
    local_test_env.PrependENVPath(avango.build.get_library_search_path_env(), Dir('../..').abspath)

    tests = local_test_env.Program ('TestAvangoOSGNetwork', sources)
    tests_alias = local_test_env.Alias('test-osg', tests, "${SOURCE.abspath}")

    AlwaysBuild(tests_alias)
    Alias('check-osg', tests_alias)
