SET(PYTHON_INCLUDE_SEARCH_DIRS
  ${PYTHON_INCLUDE_DIRS}
  "C:/python27/include"
)

SET(PYTHON_LIBRARY_SEARCH_DIRS
  ${PYTHON_LIBRARY_DIRS}
  "C:/Python27/libs"
)

message("-- checking for PYTHON")

IF (NOT PYTHON_INCLUDE_DIRS OR PYTHON_INCLUDE_DIRS STREQUAL "NOT FOUND")
    SET(_PYTHON_FOUND_INC_DIRS "")
    FOREACH(_SEARCH_DIR ${PYTHON_INCLUDE_SEARCH_DIRS})
        FIND_PATH(_CUR_SEARCH
            NAMES pyconfig.h
                PATHS ${_SEARCH_DIR}
                NO_DEFAULT_PATH)
        IF (_CUR_SEARCH)
            LIST(APPEND _PYTHON_FOUND_INC_DIRS ${_CUR_SEARCH})
        ENDIF(_CUR_SEARCH)
        SET(_CUR_SEARCH _CUR_SEARCH-NOTFOUND CACHE INTERNAL "internal use")
    ENDFOREACH(_SEARCH_DIR ${PYTHON_INCLUDE_SEARCH_DIRS})

    IF (NOT _PYTHON_FOUND_INC_DIRS)
        MESSAGE(SEND_ERROR "find_python.cmake: unable to find python headers")
    ELSE (NOT _PYTHON_FOUND_INC_DIRS)
        UNSET(PYTHON_INCLUDE_DIRS CACHE)
    ENDIF (NOT _PYTHON_FOUND_INC_DIRS)
	  
	  FOREACH(_INC_DIR ${_PYTHON_FOUND_INC_DIRS})
        SET(PYTHON_INCLUDE_DIRS ${PYTHON_INCLUDE_DIRS} ${_INC_DIR} CACHE PATH "Python include directory.")
    ENDFOREACH(_INC_DIR ${_PYTHON_FOUND_INC_DIRS})
    
ENDIF(NOT PYTHON_INCLUDE_DIRS OR PYTHON_INCLUDE_DIRS STREQUAL "NOT FOUND")

IF(UNIX)
	SET(PYTHON_LIB_FILENAME "libpython2.7.so")
ELSEIF(WIN32)
	SET(PYTHON_LIB_FILENAME "python27.lib")
ENDIF(UNIX)

IF ( PYTHON_INCLUDE_DIRS AND (PYTHON_LIBRARY_DIRS STREQUAL "NOT FOUND" OR NOT PYTHON_LIBRARY_DIRS ) )

    SET(_PYTHON_FOUND_LIB_DIR "")
    SET(_PYTHON_POSTFIX "")

    FOREACH(_SEARCH_DIR ${PYTHON_LIBRARY_SEARCH_DIRS})
        FIND_PATH(_CUR_SEARCH
				        NAMES ${PYTHON_LIB_FILENAME}
                PATHS ${_SEARCH_DIR}
                NO_DEFAULT_PATH)
        IF (_CUR_SEARCH)
            LIST(APPEND _PYTHON_FOUND_LIB_DIR ${_SEARCH_DIR})
        ENDIF(_CUR_SEARCH)
        SET(_CUR_SEARCH _CUR_SEARCH-NOTFOUND CACHE INTERNAL "internal use")
    ENDFOREACH(_SEARCH_DIR ${PYTHON_LIBRARY_SEARCH_DIRS})

    IF (NOT _PYTHON_FOUND_LIB_DIR)
        MESSAGE(FATAL_ERROR "find_python.cmake: unable to find python libraries")
    ELSE (NOT _PYTHON_FOUND_LIB_DIR)
		    SET(PYTHON_LIBRARY_DIRS ${_PYTHON_FOUND_LIB_DIR} CACHE PATH "The python library directory")
        message("--  found matching version ${PYTHON_LIBRARY_DIRS}")
    ENDIF (NOT _PYTHON_FOUND_LIB_DIR)
    
    FOREACH(_LIB_DIR ${_PYTHON_FOUND_LIB_DIR})
        SET(PYTHON_LIBRARIES ${PYTHON_LIB_FILENAME} CACHE FILEPATH "The python library filename.")
    ENDFOREACH(_LIB_DIR ${_PYTHON_FOUND_INC_DIRS})

ENDIF ( PYTHON_INCLUDE_DIRS AND (PYTHON_LIBRARY_DIRS STREQUAL "NOT FOUND" OR NOT PYTHON_LIBRARY_DIRS ) )

IF (NOT PYTHON_INCLUDE_DIRS OR PYTHON_INCLUDE_DIRS STREQUAL "NOT FOUND")
    SET(PYTHON_INCLUDE_DIRS "NOT FOUND" CACHE PATH "Python include directory.")
    MESSAGE(SEND_ERROR "find_python.cmake: unable to find python.")
ENDIF (NOT PYTHON_INCLUDE_DIRS OR PYTHON_INCLUDE_DIRS STREQUAL "NOT FOUND")

IF (NOT PYTHON_LIBRARY_DIRS OR PYTHON_LIBRARY_DIRS STREQUAL "NOT FOUND")
    SET(PYTHON_LIBRARY_DIRS "NOT FOUND" CACHE PATH "Python lib directory.")
    MESSAGE(SEND_ERROR "find_python.cmake: unable to find python libraries.")
ENDIF (NOT PYTHON_LIBRARY_DIRS OR PYTHON_LIBRARY_DIRS STREQUAL "NOT FOUND")
   
