# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2008 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build
unittest_env = avango.build.TestEnvironment() # We want our own headers ...

sources = Split('''
    AssertException.cpp
    Test.cpp
    Checks.cpp
    TestRunner.cpp
    TestResults.cpp
    TestReporter.cpp
    TestReporterStdout.cpp
    ReportAssert.cpp
    TestList.cpp
    TimeConstraint.cpp
    TestDetails.cpp
    MemoryOutStream.cpp
    DeferredTestReporter.cpp
    DeferredTestResult.cpp
    XmlTestReporter.cpp
    ''')

if avango.build.oshelper.os_is_windows():
    sources += Split('''
        Win32/TimeHelpers.cpp
        ''')
else:
    sources += Split('''
        Posix/SignalTranslator.cpp
        Posix/TimeHelpers.cpp
        ''')

lib = unittest_env.StaticLibrary('avangoUnitTest++', sources)

Alias('unittest', lib)
Alias('install-unittest', Install(avango.build.get_library_path(), lib))

avango.build.TestEnvironment.prepend_library_path(Dir('.').abspath)
