#! /bin/bash

##########################################################################
#                                                                        #
#  Avango Software, Copyright 2001 - 2007 Fraunhofer Gesellschaft        #
#  zur Foerderung der angewandten Forschung (FhG), Munich, Germany.      #
#                                                                        #
#  Avango Software (both binary and source code - if released) is        #
#  intellectual property owned by FhG and copyrighted by FhG worldwide.  #
#                                                                        #
#  Avango is a trademark owned by FhG.                                   #
#                                                                        #
##########################################################################

SRCDIR=`dirname $0`

echo bootstrap: Entering directory \`$SRCDIR\';
cd ${SRCDIR} ;
autoreconf --install --force --verbose ;
echo bootstrap: Leaving directory \`$SRCDIR\';
