# -*- Mode:Python -*-

##########################################################################
#                                                                        #
#  Avango Software, Copyright 2001 - 2007 Fraunhofer Gesellschaft        #
#  zur Foerderung der angewandten Forschung (FhG), Munich, Germany.      #
#                                                                        #
#  Avango Software (both binary and source code - if released) is        #
#  intellectual property owned by FhG and copyrighted by FhG worldwide.  #
#                                                                        #
#  Avango is a trademark owned by FhG.                                   #
#                                                                        #
##########################################################################

import avango.build

local_env = avango.build.PythonEnvironment()

avango.build.Environment.add_search_path('avango-python')

avango.build.add_library(local_env, 'avango-python')
avango.build.add_library(local_env, 'avango-core')
avango.build.add_library(local_env, 'avango-osg')
avango.build.add_library(local_env, 'boost_python')
avango.build.add_library(local_env, 'osg')


local_env.Prepend(LIBS=['avangoVRPN'])

vrpn_files = Split("""
    _vrpn.cpp
    """)

vrpn_python_files = Split("""
    __init__.py
    _nodes.py
    _dtrack_device.py
    _dtrack_target.py
    """)

lib = local_env.SharedLibrary("_vrpn", vrpn_files)



Alias('install-vrpn', local_env.Install(avango.build.get_python_path('avango/vrpn/'), [lib]+vrpn_python_files))

test_package_dir = '../test_package/'
avango.build.Environment.prepend_python_path(Dir(test_package_dir).abspath)
Install(test_package_dir+'avango/vrpn', lib)
avango.build.install_python(test_package_dir+'avango/vrpn', vrpn_python_files)

local_env.Install(avango.build.get_python_path('avango/vrpn'), vrpn_python_files)




#local_env.Depends(lib, vrpn_python_files)
local_env.Install(avango.build.get_python_path('avango/vrpn'), vrpn_python_files)
#local_env.Install(avango.build.get_python_path('avango/vrpn'), vrpn_python_files)
#local_env.Install(avango.build.get_python_path('avango/vrpn'), lib)   
#Alias('vrpn', lib)
#Alias('install-vrpn', avango.build.get_python_path('avango/vrpn'))

