# -*- Mode:Python -*-

##########################################################################
#                                                                        #
# This file is part of AVANGO.                                           #
#                                                                        #
# Copyright 1997 - 2009 Fraunhofer-Gesellschaft zur Foerderung der       #
# angewandten Forschung (FhG), Munich, Germany.                          #
#                                                                        #
# AVANGO is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU Lesser General Public License as         #
# published by the Free Software Foundation, version 3.                  #
#                                                                        #
# AVANGO is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU Lesser General Public       #
# License along with AVANGO. If not, see <http://www.gnu.org/licenses/>. #
#                                                                        #
##########################################################################

import avango.build
Import('tools_env')

tools_env.Append(CPPDEFINES='AV_TOOLS_LIBRARY')

sources = Split('''
    ChangeSelector.cpp
    Init.cpp
    InjectSelector.cpp
    ObjectSelector.cpp
    NameSelector.cpp
    FieldSelector.cpp
    Selector.cpp
    SingleSelector.cpp
    TargetHolder.cpp
    Tool.cpp
    TriggerSelector.cpp
    TypeSelector.cpp
    UnionSelector.cpp
    ''')

avango.build.add_library(tools_env, 'boost_regex')

if avango.build.Environment()['OPENSCENEGRAPH_SUPPORT']:
    avango.build.add_library(tools_env, 'avango-osg')
    avango.build.add_library(tools_env, 'avango-core')
    avango.build.add_library(tools_env, 'osg')
    avango.build.add_library(tools_env, 'osgUtil')
    sources += Split('''
        DragTool.cpp
        IntersectionTargetHolder.cpp
        NodePathTargetHolder.cpp
        PickSelector.cpp
        ProximitySelector.cpp
        ScaledGrabTool.cpp
        ''')

lib = tools_env.SharedLibrary('avangoTools', sources)
Alias('tools', lib)
Alias('install-tools', Install(avango.build.get_library_path(), lib))

avango.build.Environment.prepend_library_path(Dir('.').abspath)
